#pragma once

#define TOSTRING2(arg) #arg
#define TOSTRING(arg) TOSTRING2(arg)

#define IA_VERSION_MAJOR 1
#define IA_VERSION_MINOR 0
#define IA_VERSION_PATCH 0
#define IA_VERSION_BUILD 0

#define IA_PRODUCT_VERSION IA_VERSION_MAJOR, IA_VERSION_MINOR, IA_VERSION_PATCH, IA_VERSION_BUILD
#define IA_VERSION TOSTRING(IA_VERSION_MAJOR) "." TOSTRING(IA_VERSION_MINOR) "." TOSTRING(IA_VERSION_PATCH) "." TOSTRING(IA_VERSION_BUILD)


